### PR TITLE
Hicpro files

### PR DESCRIPTION
**Pull request by 0xaf1f**
From the [HiC-Pro 2.11.0 changelog](https://github.com/nservant/HiC-Pro/blob/master/CHANGELOG):
> SIGNIFICANT USER-VISIBLE CHANGES
>
> ...
>   o _allValidPairs extension is now changed to .allValidpairs

This PR supports finding files named according to both the old and new patterns.

### CODE REVIEW

**Comment by 0xaf1f** [comment]
My only concern is that the change of `_allValidPairs` to `.allValidPairs` causes it to now match the glob `*.*Pairs` (as in `verify_sample_hichipper_old()`) where it would not have before.

However, I ran pytest after doing a `rename 's/_allValidPairs$/.allValidPairs/' tests/hicpro_one/hic_results/data/d1/d1.allValidPairs` and the test still succeeded.

**Comment by 0xaf1f** [comment]
hello! I know I originally posted this at a bad time, so hopefully now is a better time for someone to take a look at this.

Thanks!

**Comment by caleblareau** [comment]
HI @0xaf1f 

Thank you so much for the pull request. I'm going to work more on facilitating some additional modifications to the input files, and this looks like a great place to start. I will accept the change and work through additional use cases to make sure that things hold up. Thank you so much for contributing!

**Comment by 0xaf1f** [comment]
No problem. By the way, it'd be helpful if you could have the release tags up-to-date on the repository here. Do you have a tag for v0.7.3, or will you be making a new point release soon?

**Comment by caleblareau** [comment]
Thanks for the note @0xaf1f; we've pushed an updated version to PyPi today.

**Comment by 0xaf1f** [comment]
Thanks! By the way, the pypi badge on your README seems to be stuck at 0.7.2. No big deal, but thought you might want to know.

**Pull request merged**
